### ISSUE TITLE
Error on last version 2.3.2

### ISSUE THREAD

**Issue by DjeyMute** [SpaicyGaming/UpgradablesPets#16]
When a player with a pet die...

[23:24:24] [Server thread/ERROR]: Could not pass event PlayerRespawnEvent to UpgradablesPets v2.3.2
java.lang.NullPointerException: null
	at io.github.spaicygaming.upgradablespets.x.k(x.java:30) ~[?:?]
	at io.github.spaicygaming.upgradablespets.X.a(X.java:3) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor491.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-221]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.14.4.jar:git-Paper-221]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-221]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.PlayerList.moveToWorld(PlayerList.java:673) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.PlayerList.moveToWorld(PlayerList.java:598) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2071) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.PacketPlayInClientCommand.a(SourceFile:31) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.PacketPlayInClientCommand.a(SourceFile:8) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-221]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]

**Comment by SpaicyGaming** [comment]
Thank you for the report. That bug was there since December 2018. It happed only on specific circumstances, that's why it hasn't been found since now.
